### ISSUE TITLE
Please publish com.releasehub on the Gradle plugin portal

### ISSUE THREAD

**Issue by jmfayard** [releaseshub/releases-hub-gradle-plugin#31]
Hello,
your plugin seems really useful. 
An easy way to make it better is to publish it on the Gradle Plugins Portal, so that we can use the newer, better plugins block instead of the legacy old school `buildscript` block.

```
plugins {
  id("com.releaseshub.releases-hub") version "x.y.z"
}
```

I can help you with that if you don't know how to do it, I did it for my own plugin, see here 

https://plugins.gradle.org/plugin/de.fayard.buildSrcVersions

**Comment by maxirosson** [comment]
https://github.com/releaseshub/releases-hub-gradle-plugin/issues/32
