### ISSUE TITLE
Publish on Gradle plugin portal

### ISSUE THREAD

**Issue by maxirosson** [releaseshub/releases-hub-gradle-plugin#32]

**Comment by jmfayard** [comment]
You need on account on https://plugins.gradle.org
The first time you publish, it needs to be approved by Gradle. 
Here are their criterias https://blog.gradle.org/new-plugin-portal-acceptance-criteria

You can have a look at how I configured my plugin here
https://github.com/jmfayard/buildSrcVersions/blob/11993125d2394c670980ef665b47209e0aa064bc/plugin/build.gradle.kts#L3-L50

**Comment by maxirosson** [comment]
The plugin v1.2.0 will be published to Gradle plugin portal
