### ISSUE TITLE
Question: how to exclude the Gradle wrapper from the updates?

### ISSUE THREAD

**Issue by Fondesa** [releaseshub/releases-hub-gradle-plugin#62]
I'd like to exclude the updates of the Gradle wrapper until the issue #59 won't be closed.

Quoting your doc on `excludes`:
> You can define a groupId to match all the artifacts for that group id, or groupId:artifactId to match a particular artifact. By default there aren't excluded dependencies.

How can I exclude the updates of the wrapper?

**Comment by maxirosson** [comment]
Hi. You should use the key "gradle". For example:

`
excludes = ["gradle"]
`

I am going to clarify this on the README. Thanks for your question

**Comment by Fondesa** [comment]
Thanks very much for the quick support. I'm going to close the issue.
