### ISSUE TITLE
Dependencies to upgrade not listed in the report

### ISSUE THREAD

**Issue by Fondesa** [releaseshub/releases-hub-gradle-plugin#63]
**Describe the bug**
The Gradle task `listDependenciesToUpgrade` doesn't seem to work with some dependencies (e.g. Kotlin stdlib).

**To Reproduce**
To reproduce the bug, you can go on my repo: https://github.com/Fondesa/KPermissions.
It's configured with the latest version of ReleasesHub.
The configuration is [here](https://github.com/Fondesa/KPermissions/blob/master/build.gradle#L35).
The dependencies are [here](https://github.com/Fondesa/KPermissions/blob/master/buildSrc/src/main/kotlin/Deps.kt).
As you can see, the Kotlin dependencies have the version `1.3.61`. 
Launching the task `listDependenciesToUpgrade` should list their upgrades to the version `1.3.70`.
Additional info:
- It works with the other dependencies (e.g. if you downgrade Mockito to `3.3.0`, the version `3.3.1` is listed)
- Upgrading the Kotlin dependencies manually to the version `1.3.70`, without any changes to all the other files, works

**Expected behavior**
Launching the task `listDependenciesToUpgrade` should print all the upgrades from all the repos.

**Comment by maxirosson** [comment]
Fixed. It was a problem on server side, so you can retry and it should work
