### ISSUE TITLE
gradle.properties file is being updated with flags

### ISSUE THREAD

**Issue by committedteadrinker** [releaseshub/releases-hub-gradle-plugin#67]
**Describe the bug**
`gradle.properties` file keeps getting updates (intermittently) to add:
```
file.encoding=utf-8
org.gradle.jvmargs=-Xmx6g
org.gradle.caching=true
```

**To Reproduce**
1. run `./gradlew upgradeDependencies` with PR creation
2. In one of the PRs, the changes requested included the line above.

**Expected behavior**
No `gradle.properties` update for no reason. Or at least, document this somewhere the reason why.
When there is a reason, these kinds of updates shouldn't be 'additional' to the file instead, an override. Example is on the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/2604774/77268553-70e68200-6cfa-11ea-8ef0-de9f54c84522.png)

**Additional context**
There are 2 dependency groupId updates that had this issue so far for us: 
1. `com.agoda.kakao`
2. `androidx.lifecycle`
These changes seem to be added for when the first PR is generated.

**Comment by maxirosson** [comment]
Hi. This is not caused by the releases hub gradle plugin. The plugin never edits that file
