### ISSUE TITLE
Maintain same distribution type when updating the Gradle Wrapper

### ISSUE THREAD

**Issue by fondesa** [releaseshub/releases-hub-gradle-plugin#79]
**Is your feature request related to a problem? Please describe.**
When ReleasesHub updates the Gradle Wrapper, it automatically uses `bin` as distribution type since it's its default.

**Describe the solution you'd like**
I'd like ReleasesHub to maintain the same distribution type specified in the `gradle-wrapper.properties` using the following command to update the wrapper:

```bash
./gradlew wrapper --gradle-version $version --distribution-type $distType
```

**Comment by maxirosson** [comment]
It seems that automatically uses `all`, not `bin`. Do you need to use `bin`?

**Comment by fondesa** [comment]
Mmh, it seems to use `bin` automatically as expected, both in Gradle docs and in practice.
Gradle docs: https://docs.gradle.org/current/userguide/gradle_wrapper.html
A PR of one of my repo updating the Gradle Wrapper and changing the distribution type from `all` to `bin`: https://github.com/fondesa/recycler-view-divider/pull/91

**Comment by maxirosson** [comment]
You should add this to your build.gradle

```
wrapper {
	distributionType = Wrapper.DistributionType.ALL
}
```

**Comment by fondesa** [comment]
You are right, it's better to define a default of the wrapper instead of implementing this logic into `ReleasesHub`. Thanks.
